const INDUSTRY_PROFILES = [
  {
    industry: "银行",
    concepts: ["高股息", "国企改革", "中特估"],
    summary: "盈利稳定、分红友好，适合作为小资金高集中持仓中的压舱石。",
    riskNote: "净息差和宏观信用环境变化会影响估值中枢。",
    basePrice: 11.8,
    baseMetrics: {
      businessQuality: 82,
      profitability: 78,
      cashFlow: 84,
      balanceSheet: 88,
      valuation: 80,
      stability: 86,
      industryProsperity: 66,
      conceptHeat: 30,
      catalyst: 58,
      liquidity: 84,
      concentrationFit: 88,
      volatilityFit: 82,
    },
    names: ["申海银行", "江汉银行", "华宁银行", "远川银行", "泽州银行"],
  },
  {
    industry: "电力",
    concepts: ["高股息", "火电修复", "绿电"],
    summary: "现金流和分红属性较强，兼顾防守与一定景气改善逻辑。",
    riskNote: "煤价、电价政策及装机节奏会影响盈利兑现。",
    basePrice: 8.6,
    baseMetrics: {
      businessQuality: 76,
      profitability: 74,
      cashFlow: 80,
      balanceSheet: 73,
      valuation: 77,
      stability: 79,
      industryProsperity: 71,
      conceptHeat: 42,
      catalyst: 65,
      liquidity: 78,
      concentrationFit: 79,
      volatilityFit: 76,
    },
    names: ["远川电力", "华澜能源", "申岳电网", "沐江电力", "金穗电能"],
  },
  {
    industry: "食品饮料",
    concepts: ["消费复苏", "品牌升级", "高端白酒"],
    summary: "品牌与渠道带来的护城河较明显，是 Buffett 风格下的重要质量池。",
    riskNote: "需求恢复速度与渠道库存去化会影响估值弹性。",
    basePrice: 36.4,
    baseMetrics: {
      businessQuality: 88,
      profitability: 84,
      cashFlow: 86,
      balanceSheet: 80,
      valuation: 68,
      stability: 83,
      industryProsperity: 62,
      conceptHeat: 38,
      catalyst: 56,
      liquidity: 75,
      concentrationFit: 78,
      volatilityFit: 74,
    },
    names: ["禾川酿造", "景宁食品", "澜亭饮业", "瑞谷乳业", "云岭白酒"],
  },
  {
    industry: "医药生物",
    concepts: ["创新药", "医疗服务", "中药"],
    summary: "行业分化明显，优选现金流和产品壁垒兼具的稳健型公司。",
    riskNote: "政策定价和研发不确定性会带来估值波动。",
    basePrice: 28.9,
    baseMetrics: {
      businessQuality: 80,
      profitability: 76,
      cashFlow: 73,
      balanceSheet: 77,
      valuation: 72,
      stability: 72,
      industryProsperity: 68,
      conceptHeat: 51,
      catalyst: 61,
      liquidity: 70,
      concentrationFit: 71,
      volatilityFit: 66,
    },
    names: ["景岳医药", "泽康生物", "华宁中药", "申合医疗", "瑞盈制药"],
  },
  {
    industry: "家用电器",
    concepts: ["白电龙头", "出口链", "家居消费"],
    summary: "成熟制造业中的优秀生意，重在品牌、渠道和现金流质量。",
    riskNote: "原材料与海外需求波动会影响盈利修复节奏。",
    basePrice: 24.2,
    baseMetrics: {
      businessQuality: 85,
      profitability: 80,
      cashFlow: 84,
      balanceSheet: 79,
      valuation: 73,
      stability: 82,
      industryProsperity: 64,
      conceptHeat: 28,
      catalyst: 52,
      liquidity: 72,
      concentrationFit: 76,
      volatilityFit: 78,
    },
    names: ["东庭家电", "华岳电器", "宁川智家", "瑞朗家居", "金禾厨电"],
  },
  {
    industry: "通信设备",
    concepts: ["算力网络", "光模块", "高速连接"],
    summary: "景气度和主题催化较强，但要防止热度凌驾于质量之上。",
    riskNote: "客户资本开支放缓时，估值与盈利可能双杀。",
    basePrice: 31.6,
    baseMetrics: {
      businessQuality: 71,
      profitability: 69,
      cashFlow: 65,
      balanceSheet: 72,
      valuation: 63,
      stability: 64,
      industryProsperity: 84,
      conceptHeat: 84,
      catalyst: 82,
      liquidity: 82,
      concentrationFit: 63,
      volatilityFit: 52,
    },
    names: ["联岳通信", "华穹光联", "云景连接", "瑞芯网络", "启航高速链路"],
  },
  {
    industry: "电子",
    concepts: ["半导体", "国产替代", "AI终端"],
    summary: "成长想象力较强，但只有估值合理且质量过线时才进入前排。",
    riskNote: "周期与库存扰动对情绪影响较大。",
    basePrice: 44.8,
    baseMetrics: {
      businessQuality: 68,
      profitability: 66,
      cashFlow: 60,
      balanceSheet: 70,
      valuation: 58,
      stability: 60,
      industryProsperity: 80,
      conceptHeat: 86,
      catalyst: 79,
      liquidity: 77,
      concentrationFit: 58,
      volatilityFit: 44,
    },
    names: ["申科微电", "启元芯材", "盛图半导体", "华澈封测", "曜石终端"],
  },
  {
    industry: "机械设备",
    concepts: ["机器人", "自动化", "高端制造"],
    summary: "适合作为均衡型组合中的成长辅助，但更依赖景气延续。",
    riskNote: "订单兑现与资本开支转弱时弹性会明显收缩。",
    basePrice: 22.7,
    baseMetrics: {
      businessQuality: 72,
      profitability: 70,
      cashFlow: 67,
      balanceSheet: 74,
      valuation: 69,
      stability: 68,
      industryProsperity: 76,
      conceptHeat: 74,
      catalyst: 72,
      liquidity: 74,
      concentrationFit: 65,
      volatilityFit: 56,
    },
    names: ["华策自动化", "景升装备", "远航机器人", "澜虎机械", "宁锐工业"],
  },
  {
    industry: "煤炭",
    concepts: ["高股息", "红利资产", "资源品"],
    summary: "现金流和股息属性突出，是价值投资里典型的估值与分红池。",
    riskNote: "商品价格回落时盈利中枢会下移。",
    basePrice: 18.5,
    baseMetrics: {
      businessQuality: 77,
      profitability: 82,
      cashFlow: 86,
      balanceSheet: 76,
      valuation: 83,
      stability: 73,
      industryProsperity: 74,
      conceptHeat: 46,
      catalyst: 63,
      liquidity: 79,
      concentrationFit: 80,
      volatilityFit: 70,
    },
    names: ["泰岳煤业", "景川能源", "广宁煤炭", "瑞丰资源", "华岭动力煤"],
  },
  {
    industry: "交通运输",
    concepts: ["港口航运", "公路铁路", "高股息"],
    summary: "公用属性较强，适合寻找分红稳定且估值不过热的个体。",
    riskNote: "运价和客货流量恢复节奏会影响业绩兑现。",
    basePrice: 14.9,
    baseMetrics: {
      businessQuality: 74,
      profitability: 72,
      cashFlow: 79,
      balanceSheet: 72,
      valuation: 78,
      stability: 76,
      industryProsperity: 63,
      conceptHeat: 34,
      catalyst: 54,
      liquidity: 70,
      concentrationFit: 75,
      volatilityFit: 77,
    },
    names: ["华港航运", "瑞宁公路", "申远铁路", "景州物流", "盛川港务"],
  },
  {
    industry: "公用事业",
    concepts: ["水务", "燃气", "高股息"],
    summary: "偏防守型现金流资产，适合作为价值框架下的底仓候选。",
    riskNote: "公用定价与资本开支压力会影响分红持续性。",
    basePrice: 10.4,
    baseMetrics: {
      businessQuality: 79,
      profitability: 75,
      cashFlow: 81,
      balanceSheet: 78,
      valuation: 81,
      stability: 84,
      industryProsperity: 60,
      conceptHeat: 26,
      catalyst: 49,
      liquidity: 71,
      concentrationFit: 83,
      volatilityFit: 83,
    },
    names: ["华清水务", "申城燃气", "广澜环保", "瑞安公服", "泽州公共能源"],
  },
  {
    industry: "计算机",
    concepts: ["人工智能", "政务数字化", "云服务"],
    summary: "主题辅助意义较强，但首版排序中必须受价值阈值约束。",
    riskNote: "估值弹性大，若盈利兑现跟不上热度，容易明显回撤。",
    basePrice: 38.3,
    baseMetrics: {
      businessQuality: 64,
      profitability: 60,
      cashFlow: 55,
      balanceSheet: 69,
      valuation: 52,
      stability: 58,
      industryProsperity: 82,
      conceptHeat: 90,
      catalyst: 86,
      liquidity: 76,
      concentrationFit: 52,
      volatilityFit: 35,
    },
    names: ["云岳科技", "申图智能", "启航软件", "景川云服", "华曜数字"],
  },
];

const SPECIAL_CASES = [
  {
    code: "600990",
    name: "示例ST能源",
    market: "SH",
    industry: "煤炭",
    concepts: ["风险警示"],
    isST: true,
    isSuspended: false,
    listingYears: 10,
    recentProfitYears: 4,
    hasCompleteFinancials: true,
    liquidityScore: 72,
    price: 5.4,
    lotCost: 540,
    dividendYield: 0,
    metrics: {
      businessQuality: 48,
      profitability: 40,
      cashFlow: 39,
      balanceSheet: 32,
      valuation: 66,
      stability: 28,
      industryProsperity: 38,
      conceptHeat: 10,
      catalyst: 12,
      liquidity: 72,
      concentrationFit: 30,
      volatilityFit: 26,
    },
    summary: "风险样例，默认应被过滤。",
    riskNote: "ST 风险。",
    riskFlags: ["风险警示"],
  },
  {
    code: "301188",
    name: "示例新股科技",
    market: "SZ",
    industry: "计算机",
    concepts: ["人工智能"],
    isST: false,
    isSuspended: false,
    listingYears: 1,
    recentProfitYears: 1,
    hasCompleteFinancials: true,
    liquidityScore: 80,
    price: 46.8,
    lotCost: 4680,
    dividendYield: 0.2,
    metrics: {
      businessQuality: 65,
      profitability: 48,
      cashFlow: 44,
      balanceSheet: 70,
      valuation: 45,
      stability: 41,
      industryProsperity: 83,
      conceptHeat: 94,
      catalyst: 89,
      liquidity: 80,
      concentrationFit: 46,
      volatilityFit: 28,
    },
    summary: "样例新股，默认应被过滤。",
    riskNote: "上市时间过短。",
    riskFlags: ["样本期不足"],
  },
  {
    code: "002877",
    name: "示例亏损消费",
    market: "SZ",
    industry: "食品饮料",
    concepts: ["消费复苏"],
    isST: false,
    isSuspended: false,
    listingYears: 6,
    recentProfitYears: 0,
    hasCompleteFinancials: true,
    liquidityScore: 64,
    price: 9.7,
    lotCost: 970,
    dividendYield: 0.3,
    metrics: {
      businessQuality: 52,
      profitability: 28,
      cashFlow: 34,
      balanceSheet: 55,
      valuation: 62,
      stability: 26,
      industryProsperity: 46,
      conceptHeat: 18,
      catalyst: 25,
      liquidity: 64,
      concentrationFit: 40,
      volatilityFit: 42,
    },
    summary: "样例亏损公司，默认应被过滤。",
    riskNote: "长期亏损。",
    riskFlags: ["盈利质量差"],
  },
];

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function wobble(seed, iteration, amplitude) {
  return Math.sin((seed + 1) * 1.618 + iteration * 0.82) * amplitude;
}

function buildStock(profile, industryIndex, name, nameIndex, iteration) {
  const seed = industryIndex * 10 + nameIndex;
  const metrics = {};

  for (const [key, value] of Object.entries(profile.baseMetrics)) {
    const drift = wobble(seed + value, iteration, key === "conceptHeat" ? 6.8 : 4.2);
    const personality = wobble(seed * 2 + value, 1, 3.5);
    metrics[key] = Math.round(clamp(value + drift + personality, 28, 94));
  }

  // 派生新增维度（philosophy v2 兼容）
  metrics.businessModelQuality = metrics.businessModelQuality ?? metrics.businessQuality;
  metrics.managementQuality =
    metrics.managementQuality ??
    Math.round(clamp(
      (metrics.businessQuality ?? 70) * 0.6 + (metrics.stability ?? 70) * 0.3 + (metrics.profitability ?? 70) * 0.1,
      30,
      90,
    ));

  const market = nameIndex % 2 === 0 ? "SH" : "SZ";
  const codeBase = market === "SH" ? 600000 : 300000;
  const code = String(codeBase + industryIndex * 100 + nameIndex + 10);
  const price = clamp(profile.basePrice + wobble(seed, iteration, profile.basePrice * 0.12), 5, 198);
  const lotCost = Math.round(price * 100);
  const dividendYield = clamp(
    round(1.2 + metrics.valuation / 25 + metrics.cashFlow / 40 - metrics.conceptHeat / 60),
    0.1,
    8.8,
  );

  return {
    code,
    name,
    market,
    industry: profile.industry,
    concepts: profile.concepts,
    isST: false,
    isSuspended: false,
    listingYears: 4 + ((industryIndex + nameIndex * 3) % 13),
    recentProfitYears: 5,
    hasCompleteFinancials: true,
    liquidityScore: metrics.liquidity,
    price: round(price),
    lotCost,
    dividendYield,
    metrics,
    summary: profile.summary,
    riskNote: profile.riskNote,
    riskFlags: metrics.conceptHeat > 80 && metrics.valuation < 62 ? ["主题热度偏高"] : [],
  };
}

function round(value) {
  return Math.round(value * 100) / 100;
}

export const SAMPLE_MODE_NOTE =
  "当前为样例数据模式：用于验证筛选、排序和交互流程，后续可替换为真实 A 股数据源。";

export function createSampleSnapshot(iteration = 0) {
  const items = INDUSTRY_PROFILES.flatMap((profile, industryIndex) =>
    profile.names.map((name, nameIndex) => buildStock(profile, industryIndex, name, nameIndex, iteration)),
  );

  return {
    mode: "sample",
    generatedAt: new Date(Date.now() + iteration * 60000).toISOString(),
    note: SAMPLE_MODE_NOTE,
    items: [...items, ...SPECIAL_CASES],
  };
}
